//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeGame.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LifeGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AliveCellColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AliveCellColor {
            get {
                return ResourceManager.GetString("AliveCellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AliveCount に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AliveCellsCount {
            get {
                return ResourceManager.GetString("AliveCellsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CellBorderColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CellBorderColor {
            get {
                return ResourceManager.GetString("CellBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ChangeCells に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeCells {
            get {
                return ResourceManager.GetString("ChangeCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Col:0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coordinate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Coordinate {
            get {
                return ResourceManager.GetString("Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CurrentDirectory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CurrentDirectory {
            get {
                return ResourceManager.GetString("CurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeadCellColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeadCellColor {
            get {
                return ResourceManager.GetString("DeadCellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Generation {
            get {
                return ResourceManager.GetString("Generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IsAlive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsAlive {
            get {
                return ResourceManager.GetString("IsAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notice_LoadFailed {
            get {
                return ResourceManager.GetString("Notice_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A file with the same name exists.
        ///Do you want to overwrite it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notice_OverwriteSave {
            get {
                return ResourceManager.GetString("Notice_OverwriteSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notice_SaveFailed {
            get {
                return ResourceManager.GetString("Notice_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It takes a while because the number of cells increases.
        ///Do you want to change it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notice_TakeTime {
            get {
                return ResourceManager.GetString("Notice_TakeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   These characters can not be used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notice_UnusableString {
            get {
                return ResourceManager.GetString("Notice_UnusableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row:0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RowCol:0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RowColumn {
            get {
                return ResourceManager.GetString("RowColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SelectionMode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectionMode {
            get {
                return ResourceManager.GetString("SelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StateHistory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StateHistory {
            get {
                return ResourceManager.GetString("StateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThreeDots {
            get {
                return ResourceManager.GetString("ThreeDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LifeGame に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToNextGeneration {
            get {
                return ResourceManager.GetString("ToNextGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToPreviousGeneration {
            get {
                return ResourceManager.GetString("ToPreviousGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TraceBack に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TraceBack {
            get {
                return ResourceManager.GetString("TraceBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \/:*?&quot;&lt;&gt;| に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnusableString {
            get {
                return ResourceManager.GetString("UnusableString", resourceCulture);
            }
        }
    }
}
